export enum LogLevel {
  LOG = 'log',
  ERROR = 'error',
  WARN = 'warn',
  DEBUG = 'debug',
  VERBOSE = 'verbose',
  FATAL = 'fatal',
}

export enum LogAction {
  REGISTER = 'register',
  LOGIN = 'login',
  GET_PROFILE = 'get_profile',
  GET_ALL_USERS = 'get_all_users',
  CREATE_EVENT = 'create_event',
  GET_EVENTS = 'get_events',
  GET_EVENT = 'get_event',
  UPDATE_EVENT = 'update_event',
  DELETE_EVENT = 'delete_event',
  PUBLISH_EVENT = 'publish_event',
  CANCEL_EVENT = 'cancel_event',
  RESERVE_TICKET = 'reserve_ticket',
  CONFIRM_BOOKING = 'confirm_booking',
  EXPIRE_BOOKING = 'expire_booking',
  FAIL_BOOKING = 'fail_booking',
  CANCEL_BOOKING = 'cancel_booking',
  GET_MY_BOOKINGS = 'get_my_bookings',
  PROCESS_PAYMENT = 'process_payment',
  CHECK_AVAILABILITY = 'check_availability',
  RELEASE_HOLD = 'release_hold',
  SEND_NOTIFICATION = 'send_notification',
  GET_MY_TICKETS = 'get_my_tickets',
}
